// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ZSFUyCA-x2zxtrvBk77WsuVhYtS0fuQ',
    appId: '1:650673979964:web:e6da5febf86c7abad3b939',
    messagingSenderId: '650673979964',
    projectId: 'que-pasa-en-tu-barrio',
    authDomain: 'que-pasa-en-tu-barrio.firebaseapp.com',
    storageBucket: 'que-pasa-en-tu-barrio.firebasestorage.app',
    measurementId: 'G-X8F4YT9QT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeBjOxDmiZSAjGi00I7TD5UED6UmEVkJg',
    appId: '1:650673979964:android:c9cb7350c01d0277d3b939',
    messagingSenderId: '650673979964',
    projectId: 'que-pasa-en-tu-barrio',
    storageBucket: 'que-pasa-en-tu-barrio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkcmwvTvpjeO4Po3mcahCV1Xb3NRrYhWs',
    appId: '1:650673979964:ios:016eb29e4266a07cd3b939',
    messagingSenderId: '650673979964',
    projectId: 'que-pasa-en-tu-barrio',
    storageBucket: 'que-pasa-en-tu-barrio.firebasestorage.app',
    iosBundleId: 'com.quepasaentubarrio.quePasaEnTuBarrio',
  );
}
